// gun_ammo.js - GENERATED by tools/gen_gun_ammo.py. Do not hand-edit.
//
// Salvage trades levels for ammo, and ammo in TaCZ is one item whose calibre
// lives in custom_data under AmmoId. A held gun reports GunId but NOT its
// calibre, so this is the bridge: GunId -> AmmoId, read straight out of the
// jar's data/tacz/data/guns/*_data.json rather than guessed.
//
// Regenerate whenever TaCZ updates or a gun pack is added. A stale map hands
// out rounds that chamber in nothing - the exact failure /salvageprobe exists
// to catch.
//
// 54 guns, 19 distinct calibres.
;
var VELDORA = (typeof VELDORA !== 'undefined') ? VELDORA : {};

;(function () {
  var GUN_AMMO = {
    'tacz:aa12': 'tacz:12g',
    'tacz:ai_awp': 'tacz:338',
    'tacz:ak47': 'tacz:762x39',
    'tacz:aug': 'tacz:556x45',
    'tacz:b93r': 'tacz:9mm',
    'tacz:cz75': 'tacz:9mm',
    'tacz:db_long': 'tacz:12g',
    'tacz:db_short': 'tacz:12g',
    'tacz:deagle': 'tacz:50ae',
    'tacz:deagle_golden': 'tacz:357mag',
    'tacz:fn_evolys': 'tacz:308',
    'tacz:fn_fal': 'tacz:308',
    'tacz:g36k': 'tacz:556x45',
    'tacz:glock_17': 'tacz:9mm',
    'tacz:hk416d': 'tacz:556x45',
    'tacz:hk_g3': 'tacz:308',
    'tacz:hk_mk23': 'tacz:45acp',
    'tacz:hk_mp5a5': 'tacz:9mm',
    'tacz:kar98': 'tacz:792x57',
    'tacz:lonetrail': 'tacz:30_06',
    'tacz:m1014': 'tacz:12g',
    'tacz:m107': 'tacz:50bmg',
    'tacz:m16a1': 'tacz:556x45',
    'tacz:m16a4': 'tacz:556x45',
    'tacz:m1911': 'tacz:45acp',
    'tacz:m249': 'tacz:556x45',
    'tacz:m320': 'tacz:40mm',
    'tacz:m4a1': 'tacz:556x45',
    'tacz:m700': 'tacz:30_06',
    'tacz:m870': 'tacz:12g',
    'tacz:m95': 'tacz:50bmg',
    'tacz:m9a4': 'tacz:9mm',
    'tacz:minigun': 'tacz:308',
    'tacz:mk14': 'tacz:308',
    'tacz:p320': 'tacz:45acp',
    'tacz:p90': 'tacz:57x28',
    'tacz:qbz_191': 'tacz:58x42',
    'tacz:qbz_95': 'tacz:58x42',
    'tacz:rhino357': 'tacz:357mag',
    'tacz:rpg7': 'tacz:rpg_rocket',
    'tacz:rpk': 'tacz:762x39',
    'tacz:scar_h': 'tacz:308',
    'tacz:scar_l': 'tacz:556x45',
    'tacz:sks_tactical': 'tacz:762x39',
    'tacz:spas_12': 'tacz:12g',
    'tacz:spr15hb': 'tacz:556x45',
    'tacz:springfield1873': 'tacz:45_70',
    'tacz:taurus500': 'tacz:500mag',
    'tacz:taurus943': 'tacz:22wmr',
    'tacz:timeless50': 'tacz:50ae',
    'tacz:type_81': 'tacz:762x39',
    'tacz:ump45': 'tacz:45acp',
    'tacz:uzi': 'tacz:9mm',
    'tacz:vector45': 'tacz:45acp',
  }

  var MAG = {
    'tacz:aa12': 8,
    'tacz:ai_awp': 5,
    'tacz:ak47': 30,
    'tacz:aug': 30,
    'tacz:b93r': 20,
    'tacz:cz75': 16,
    'tacz:db_long': 2,
    'tacz:db_short': 2,
    'tacz:deagle': 7,
    'tacz:deagle_golden': 9,
    'tacz:fn_evolys': 75,
    'tacz:fn_fal': 20,
    'tacz:g36k': 30,
    'tacz:glock_17': 17,
    'tacz:hk416d': 30,
    'tacz:hk_g3': 20,
    'tacz:hk_mk23': 12,
    'tacz:hk_mp5a5': 30,
    'tacz:kar98': 4,
    'tacz:lonetrail': 1,
    'tacz:m1014': 6,
    'tacz:m107': 10,
    'tacz:m16a1': 20,
    'tacz:m16a4': 30,
    'tacz:m1911': 7,
    'tacz:m249': 75,
    'tacz:m320': 1,
    'tacz:m4a1': 30,
    'tacz:m700': 5,
    'tacz:m870': 5,
    'tacz:m95': 5,
    'tacz:m9a4': 17,
    'tacz:mk14': 10,
    'tacz:p320': 12,
    'tacz:p90': 50,
    'tacz:qbz_191': 30,
    'tacz:qbz_95': 30,
    'tacz:rhino357': 6,
    'tacz:rpg7': 1,
    'tacz:rpk': 40,
    'tacz:scar_h': 20,
    'tacz:scar_l': 30,
    'tacz:sks_tactical': 10,
    'tacz:spas_12': 5,
    'tacz:spr15hb': 15,
    'tacz:springfield1873': 1,
    'tacz:taurus500': 5,
    'tacz:taurus943': 8,
    'tacz:timeless50': 8,
    'tacz:type_81': 30,
    'tacz:ump45': 25,
    'tacz:uzi': 20,
    'tacz:vector45': 20,
  }

  // null means "not a gun we know", NEVER a default calibre. Handing out the
  // wrong rounds silently is worse than handing out none and saying so.
  VELDORA.gunAmmo = {
    of: function (gunId) { return (gunId && GUN_AMMO[String(gunId)]) || null },
    magOf: function (gunId) { return (gunId && MAG[String(gunId)]) || null },
    count: 54,
  }

  ServerEvents.loaded(function () {
    console.info('[gunammo] VELDORA.gunAmmo published OK - 54 guns, 19 calibres')
  })
})();
