name = "Cogs & Cadavers"
author = "EHtut"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92593baed5d70e773c48cb009b5050476646bc3d8b66bdaca5275cba38b78bc0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
