name = "Cogs & Cadavers"
author = "EHtut"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6293ae88cb7625a37683a5154dddb89d5629e265bf0dc18be258407d06ed66a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
