maxSavedRecordings = 200
minimumAudioCount = 500
# Default: 12
# Range: 1 ~ 100
revervoxMaxAudios = 12
# Default: 1.5
# Range: 0.0 ~ 5.0
revervoxGracePeriod = 1.5
# Default: 0.5
# Range: 0.0 ~ 5.0
revervoxBatGracePeriod = 0.5
# Default: 5
# Range: 2 ~ 500
revervoxBatSpawnChance = 60
# Default: 7
# Range: 1 ~ 20
revervoxSwordBonus = 7
# Default: 10
# Range: 1 ~ 20
batToothDropChance = 10
# Default: 100
# Range: 0 ~ 500
revervoxMinimumDistance = 100
# Default: 1.0
# Range: 0.1 ~ 20.0
batEventChance = 0.15
enableBatEvent = false
revervoxBlockBreaking = false
revervoxAboveGround = false
revervoxBreakNonSolid = true
revervoxSonicBoom = false
# Default: 35
# Range: 1 ~ 100
revervoxSonicBoomCooldown = 5
# Default: 16
# Range: 5 ~ 100
revervoxSonicBoomRange = 30
# Default: 4
# Range: 0 ~ 100
megaphoneCooldown = 4
crouchStopsMegaphone = true
# Default: 2
# Range: > 1
revervoxSpawnChance = 500
# Default: 1.0
# Range: 0.1 ~ 20.0
fakeRevervoxEventChance = 1.0
enableFakeRevervoxEvent = false
# Default: 5
# Range: 1 ~ 100
revervoxSonicBoomSecsOutOfSight = 5
# Default: 10
# Range: 1 ~ 100
revervoxUnheardBeforeDisappear = 10
# Default: 6000
# Range: > 0
revervoxSpawnCooldown = 1000000
# Default: 200.0
# Range: 1.0 ~ 1.7976931348623157E308
revervoxCooldownRange = 200.0
# Default: 10000
# Range: > 1
revervoxGiveUpTime = 10000
# Default: 300
# Range: > 1
revervoxForgetPain = 300
