#!/usr/bin/env python3
"""Generate the gun -> ammo map for E6, read out of the TaCZ jar.

Salvage's second trade is "give me your levels and i shall grant you ammo", and
ammo in TaCZ is not an item: tacz:ammo carries its calibre in custom_data under
AmmoId, across ~20 types. So to hand a player rounds that actually chamber, the
trade must know which ammo the gun in their hand takes.

A held gun's custom_data gives GunId (e.g. tacz:glock_17) but NOT its calibre. The
mapping lives in the jar, at data/tacz/data/guns/<gun>_data.json:

    {"ammo": "tacz:9mm", "ammo_amount": 17, ...}

This reads all of them and writes a KubeJS data script. Regenerate whenever TaCZ
updates or a gun pack is added - a stale map hands out rounds that fit nothing,
which is exactly the failure the E6 probe was written to prevent.

    python tools/gen_gun_ammo.py
"""
import glob
import json
import os
import pathlib
import re
import sys
import zipfile

BASE = pathlib.Path(__file__).resolve().parent.parent.parent
OUT = BASE / 'repo' / 'pack' / 'kubejs' / 'server_scripts' / 'gun_ammo.js'


def loads_lenient(raw: bytes):
    """Parse a mod's JSON that is really JSON5.

    ⚠️ 45 of TaCZ's 54 gun files carry `//` comments (in Chinese), so a strict
    json.loads fails on them. The first version of this tool treated that as "no
    ammo key" and silently emitted a map covering 9 guns out of 54 - it would have
    handed the wrong calibre to anyone holding one of the other 45, which is the
    exact failure /salvageprobe was written to prevent, one layer up.

    Same trap as instance/config/tectonic.json. Mod JSON is JSON5 until proven
    otherwise.
    """
    text = raw.decode('utf-8', 'ignore')
    out = []
    i, n = 0, len(text)
    in_str = False
    while i < n:
        c = text[i]
        if in_str:
            out.append(c)
            if c == '\\' and i + 1 < n:      # keep escapes intact
                out.append(text[i + 1])
                i += 2
                continue
            if c == '"':
                in_str = False
            i += 1
            continue
        if c == '"':
            in_str = True
            out.append(c)
            i += 1
            continue
        if c == '/' and i + 1 < n and text[i + 1] == '/':
            while i < n and text[i] != '\n':
                i += 1
            continue
        if c == '/' and i + 1 < n and text[i + 1] == '*':
            i += 2
            while i + 1 < n and not (text[i] == '*' and text[i + 1] == '/'):
                i += 1
            i += 2
            continue
        out.append(c)
        i += 1
    stripped = re.sub(r',(\s*[}\]])', r'\1', ''.join(out))   # trailing commas
    return json.loads(stripped)


def main() -> int:
    jars = glob.glob(str(BASE / 'instance' / 'mods' / 'tacz-neoforge*.jar'))
    if not jars:
        print('no tacz jar found')
        return 1
    z = zipfile.ZipFile(jars[0])

    mapping = {}
    amounts = {}
    for name in z.namelist():
        m = re.search(r'/data/tacz/data/guns/([a-z0-9_]+)_data\.json$', name)
        if not m:
            continue
        try:
            d = loads_lenient(z.read(name))
        except Exception as e:
            print('  !! could not parse %s :: %s' % (name.split('/')[-1], e))
            continue
        ammo = d.get('ammo')
        if not ammo:
            continue
        mapping['tacz:' + m.group(1)] = ammo
        if isinstance(d.get('ammo_amount'), int):
            amounts['tacz:' + m.group(1)] = d['ammo_amount']

    # A partial map is worse than none: it hands the wrong calibre to every gun it
    # missed, silently. Fail loudly if we did not read every gun file present.
    total = len([n for n in z.namelist()
                 if re.search(r'/data/tacz/data/guns/[a-z0-9_]+\.json$', n)])
    if not mapping:
        print('no gun data found in %s' % os.path.basename(jars[0]))
        return 1
    if len(mapping) != total:
        print('!! read %d of %d gun files - REFUSING to write a partial map'
              % (len(mapping), total))
        return 1

    calibres = sorted(set(mapping.values()))
    lines = [
        '// gun_ammo.js - GENERATED by tools/gen_gun_ammo.py. Do not hand-edit.',
        '//',
        '// Salvage trades levels for ammo, and ammo in TaCZ is one item whose calibre',
        '// lives in custom_data under AmmoId. A held gun reports GunId but NOT its',
        '// calibre, so this is the bridge: GunId -> AmmoId, read straight out of the',
        '// jar\'s data/tacz/data/guns/*_data.json rather than guessed.',
        '//',
        '// Regenerate whenever TaCZ updates or a gun pack is added. A stale map hands',
        '// out rounds that chamber in nothing - the exact failure /salvageprobe exists',
        '// to catch.',
        '//',
        '// %d guns, %d distinct calibres.' % (len(mapping), len(calibres)),
        ';',
        "var VELDORA = (typeof VELDORA !== 'undefined') ? VELDORA : {};",
        '',
        ';(function () {',
        '  var GUN_AMMO = {',
    ]
    for g in sorted(mapping):
        lines.append("    '%s': '%s'," % (g, mapping[g]))
    lines.append('  }')
    lines.append('')
    lines.append('  var MAG = {')
    for g in sorted(amounts):
        lines.append("    '%s': %d," % (g, amounts[g]))
    lines.append('  }')
    lines.append('')
    lines += [
        '  // null means "not a gun we know", NEVER a default calibre. Handing out the',
        '  // wrong rounds silently is worse than handing out none and saying so.',
        '  VELDORA.gunAmmo = {',
        '    of: function (gunId) { return (gunId && GUN_AMMO[String(gunId)]) || null },',
        '    magOf: function (gunId) { return (gunId && MAG[String(gunId)]) || null },',
        '    count: %d,' % len(mapping),
        '  }',
        '',
        '  ServerEvents.loaded(function () {',
        "    console.info('[gunammo] VELDORA.gunAmmo published OK - %d guns, %d calibres')"
        % (len(mapping), len(calibres)),
        '  })',
        '})();',
        '',
    ]
    OUT.write_text('\n'.join(lines), encoding='utf-8')
    print('wrote %s' % OUT.relative_to(BASE))
    print('  %d guns, %d calibres: %s' % (len(mapping), len(calibres),
                                          ', '.join(c.split(':')[1] for c in calibres)))
    print('  sample: tacz:glock_17 -> %s' % mapping.get('tacz:glock_17', '?'))
    return 0


if __name__ == '__main__':
    sys.exit(main())
